// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxjZM9wJq4uQ7qL2ibfeui5ghQyYRGH0M',
    appId: '1:708471987934:web:a11410f552a63ddc06ec4f',
    messagingSenderId: '708471987934',
    projectId: 'pure-blend-smoothies',
    authDomain: 'pure-blend-smoothies.firebaseapp.com',
    storageBucket: 'pure-blend-smoothies.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjNCSAee63GD0LewPiBKga9hzG6VLhHYM',
    appId: '1:708471987934:android:fb14d7588b17d15306ec4f',
    messagingSenderId: '708471987934',
    projectId: 'pure-blend-smoothies',
    storageBucket: 'pure-blend-smoothies.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmEmiZF2q99PxRgCA_rGUyvz6uay8zues',
    appId: '1:708471987934:ios:6f5a32c9d1497fe706ec4f',
    messagingSenderId: '708471987934',
    projectId: 'pure-blend-smoothies',
    storageBucket: 'pure-blend-smoothies.firebasestorage.app',
    iosBundleId: 'com.example.pureBlendSmoothieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmEmiZF2q99PxRgCA_rGUyvz6uay8zues',
    appId: '1:708471987934:ios:6f5a32c9d1497fe706ec4f',
    messagingSenderId: '708471987934',
    projectId: 'pure-blend-smoothies',
    storageBucket: 'pure-blend-smoothies.firebasestorage.app',
    iosBundleId: 'com.example.pureBlendSmoothieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxjZM9wJq4uQ7qL2ibfeui5ghQyYRGH0M',
    appId: '1:708471987934:web:83963aa2d3ce7ef806ec4f',
    messagingSenderId: '708471987934',
    projectId: 'pure-blend-smoothies',
    authDomain: 'pure-blend-smoothies.firebaseapp.com',
    storageBucket: 'pure-blend-smoothies.firebasestorage.app',
  );
}
